@startuml

actor Browser
participant HttpServer
participant CreateSurveyController
participant CreateSurveyTitleController
participant UpdateSurveyController
participant ListQuestionsForSurvey
participant QuestionOptionController
participant SaveAnswerController
participant SurveyOptionsController
participant QuestionDao
database survey_db


Browser --> HttpServer: POST /api/surveys
HttpServer -> controllers: get ("/api/surveys")
HttpServer <-- controllers: CreateSurveyTitleController
HttpServer -> CreateSurveyTitleController: handle
CreateSurveyTitleController -> CreateSurveyTitleController: Survey survey = new Survey()
CreateSurveyTitleController -> CreateSurveyTitleController: survey.setTitle(parameters.get("title"));
CreateSurveyTitleController -> SurveyDao: save(survey);
SurveyDao -> Survey_db: Insert into survey ...
Browser <-- HttpServer: 303 Location: firstStepSurvey.html


Browser --> HttpServer: POST /api/questions
HttpServer -> controllers: get ("/api/questions")
HttpServer <-- controllers: CreateSurveyController
HttpServer -> CreateSurveyController: handle
CreateSurveyController -> CreateSurveyController: Question question = new Question()
CreateSurveyController -> CreateSurveyController: question.setTitle(queryMap.get("fstittel"));
CreateSurveyController -> CreateSurveyController: question.setText(queryMap.get("fspm"));
CreateSurveyController -> CreateSurveyController: question.setAnswerOne(queryMap.get("answerEn"));
CreateSurveyController -> CreateSurveyController: question.setAnswerTwo(queryMap.get("answerTo"));
CreateSurveyController -> CreateSurveyController: question.setSurvey_ID(Long.parseLong(queryMap.get("questions")));
CreateSurveyController -> CreateSurveyController: question.setText(queryMap.get("fspm"));
CreateSurveyController -> QuestionDao: save(question);
QuestionDao -> Survey_db: INSERT INTO QUESTION ...
Browser <-- HttpServer: 303 Location: createSurvey.html

Browser --> HttpServer: POST /api/updateSurvey
HttpServer -> controllers: get ("/api/updateSurvey")
HttpServer <-- controllers: UpdateSurveyController
HttpServer -> UpdateSurveyController: handle
UpdateSurveyController -> UpdateSurveyController: Question question = new Question()
UpdateSurveyController -> UpdateSurveyController: question.setTitle(queryMap.get("fstittel"));
UpdateSurveyController -> UpdateSurveyController: question.setText(queryMap.get("fspm"));
UpdateSurveyController -> UpdateSurveyController: question.setAnswerOne(queryMap.get("answerEn"));
UpdateSurveyController -> UpdateSurveyController: question.setAnswerTwo(queryMap.get("answerTo"));
UpdateSurveyController -> UpdateSurveyController: question.setAnswerThree(queryMap.get("answerTre"));
UpdateSurveyController -> UpdateSurveyController: question.setSurvey_ID(Long.parseLong(queryMap.get("questionTitle")));
UpdateSurveyController -> QuestionDao: update(question)
QuestionDao -> Survey_db: UPDATE question SET ...
Browser <-- HttpServer: 303 Location: updateSurvey.html

Browser --> HttpServer: /api/showQuestions
HttpServer -> controllers: get("/api/showQuestions")



@enduml